# Generated by Django 5.2.7 on 2025-11-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
