# Generated by Django 5.2.7 on 2025-11-11 03:58

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_image_bookimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimages',
            name='image',
            field=models.ImageField(upload_to='Books/images', validators=[books.validators.validate_file_size]),
        ),
    ]
