# Generated by Django 5.2.7 on 2025-11-12 04:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_bookimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
